"""Pocetna2 migracija shopDB.

Revision ID: 5d38535ecef8
Revises: a72342abae98
Create Date: 2023-07-04 21:57:41.674472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d38535ecef8'
down_revision = 'a72342abae98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sold', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('waiting', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], name='statistics_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
