"""Pocetna2 migracija shopDB.

Revision ID: ffa9dad61710
Revises: 5d38535ecef8
Create Date: 2023-07-05 00:33:20.669204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa9dad61710'
down_revision = '5d38535ecef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_order', 'price')
    # ### end Alembic commands ###
