version: '3'

services:

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - authenticationNetwork
      - shopNetwork
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3307:3306
    volumes:
      - authenticationVolume:/var/lib/mysql
    networks:
      - authenticationNetwork
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      authenticationDatabase:
        condition: service_healthy
    networks:
      - authenticationNetwork
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      - authenticationDBMigration
    ports:
      - 5002:5002
    networks:
      - authenticationNetwork

  shopDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3308:3306
    volumes:
      - shopVolume:/var/lib/mysql
    networks:
      - shopNetwork

  migrationShop:
    image: shopdbmigration
    environment:
      - DATABASE_URL=shopDatabase
    depends_on:
      shopDatabase:
        condition: service_healthy
    networks:
      - shopNetwork
  owner:
    image: owner
    environment:
      - DATABASE_URL=shopDatabase
    depends_on:
      - migrationShop
    ports:
      - 5000:5000
    networks:
      - shopNetwork

  buyer:
    image: buyer
    environment:
      - DATABASE_URL=shopDatabase
    depends_on:
      - migrationShop
    ports:
      - 5003:5003
    networks:
      - shopNetwork

  courier:
    image: courier
    environment:
      - DATABASE_URL=shopDatabase
    depends_on:
      - migrationShop
    ports:
      - 5004:5004
    networks:
      - shopNetwork

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-mastera
    ports:
      - 8081:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - shopNetwork
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1a
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shopNetwork
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2a
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shopNetwork
  sparkapp:
    image: sparkowner
    environment:
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=sparkowner
      - DATABASE_URL=shopDatabase
    ports:
      - 5005:5005
    networks:
      - shopNetwork




volumes:
  authenticationVolume:
  shopVolume:

networks:
  authenticationNetwork:
  shopNetwork: